apiVersion: v1
kind: List
items:
- apiVersion: apps/v1beta1
  kind: StatefulSet
  metadata:
    name: elasticsearch
    labels:
      app: elasticsearch
  spec:
    serviceName: elasticsearch
    replicas: 1
    selector:
      matchLabels:
        app: elasticsearch
    serviceName: elasticsearch
    template:
      metadata:
        labels:
          app: elasticsearch
      spec:
        initContainers:
        - name: init-sysctl
          image: busybox
          command:
            - "sysctl"
            - "-w"
            - "vm.max_map_count=262144"
          securityContext:
            privileged: true
        containers:
        - env:
          - name: SERVICE
            value: elasticsearch
          - name: LOG_LEVEL
            value: info
          image: registry.centos.org/rhsyseng/elasticsearch:latest
          imagePullPolicy: Always
          name: elasticsearch
          livenessProbe:
            httpGet:
              path: /
              port: 9200
          livenessProbe:
            httpGet:
              path: /
              port: 9200
          ports:
          - containerPort: 9200
            name: elasticsearch
            protocol: TCP
          - containerPort: 9300
            name: transport
            protocol: TCP
          resources:
            limits:
              memory: 512Mi
            requests:
              memory: 512Mi
          volumeMounts:
          - mountPath: /elasticsearch/persistent
            name: elasticsearch-persistent
        securityContext: {}
        volumes:
        - emptyDir: {}
          name: elasticsearch-persistent
- apiVersion: v1
  kind: Service
  metadata:
    name: elasticsearch
    labels:
      app: jaeger
      jaeger-infra: elasticsearch-service
  spec:
    clusterIP: None
    selector:
      app: jaeger-elasticsearch
    ports:
    - port: 9200
      name: elasticsearch
    - port: 9300
      name: transport
