apiVersion: v1
kind: List
items:
- apiVersion: apps/v1beta1
  kind: StatefulSet
  metadata:
    name: elasticsearch
    labels:
      app: elasticsearch
  spec:
    serviceName: elasticsearch
    replicas: 1
    selector:
      matchLabels:
        app: elasticsearch
    template:
      metadata:
        labels:
          app: elasticsearch
      spec:
        serviceAccountName: privilegeduser
        initContainers:
          - name: init-sysctl
            image: busybox
            imagePullPolicy: IfNotPresent
            command:
              - "sysctl"
              - "-w"
              - "vm.max_map_count=262144"
            securityContext:
              privileged: true			  
        containers:
        - env:
          - name: SERVICE
            value: elasticsearch
          - name: LOG_LEVEL
            value: info
          image: registry.centos.org/rhsyseng/elasticsearch:latest
          imagePullPolicy: Always
          name: elasticsearch
          livenessProbe:
            httpGet:
              path: /_cluster/health
              port: 9200
              scheme: HTTP
          ports:
          - containerPort: 9200
            name: elasticsearch
            protocol: TCP
          - containerPort: 9300
            name: transport
            protocol: TCP
          resources:
            limits:
              memory: 512Mi
            requests:
              memory: 512Mi
          volumeMounts:
          - mountPath: /elasticsearch/persistent
            name: elasticsearch-persistent
        securityContext: {}
        volumes:
        - emptyDir: {}
          name: elasticsearch-persistent
- apiVersion: v1
  kind: Service
  metadata:
    name: elasticsearch
    labels:
      app: jaeger
      jaeger-infra: elasticsearch-service
  spec:
    clusterIP: None
    selector:
      app: elasticsearch
    ports:
    - port: 9200
      name: elasticsearch
    - port: 9300
      name: transport