apiVersion: v1
kind: ImageStream
metadata:
  name: elasticsearch
  labels:
    app: elasticsearch
spec:
  lookupPolicy:
    local: false
  tags:
  - name: 6.2.2
    from:
      kind: DockerImage
      name: registry.centos.org/rhsyseng/elasticsearch:latest
#If you want to add other version image, delete comment      
#  - name: 6.2.1
#    from:
#      kind: DockerImage
#      name: registry.centos.org/rhsyseng/elasticsearch:6.2.1
#  - name: 6.1.2
#    from:
#      kind: DockerImage
#      name: registry.centos.org/rhsyseng/elasticsearch:6.1.2
#  - name: 5.5.2
#    from:
#      kind: DockerImage
#      name: registry.centos.org/rhsyseng/elasticsearch:5.5.2
